// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0309

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0309Client is the client API for Zhaoh0309 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0309Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0309Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0309Client(cc grpc.ClientConnInterface) Zhaoh0309Client {
	return &zhaoh0309Client{cc}
}

func (c *zhaoh0309Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0309.sample_package_0309.zhaoh0309/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0309Server is the server API for Zhaoh0309 service.
// All implementations must embed UnimplementedZhaoh0309Server
// for forward compatibility
type Zhaoh0309Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0309Server()
}

// UnimplementedZhaoh0309Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0309Server struct {
}

func (UnimplementedZhaoh0309Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedZhaoh0309Server) mustEmbedUnimplementedZhaoh0309Server() {}

// UnsafeZhaoh0309Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0309Server will
// result in compilation errors.
type UnsafeZhaoh0309Server interface {
	mustEmbedUnimplementedZhaoh0309Server()
}

func RegisterZhaoh0309Server(s grpc.ServiceRegistrar, srv Zhaoh0309Server) {
	s.RegisterService(&Zhaoh0309_ServiceDesc, srv)
}

func _Zhaoh0309_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0309Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0309.sample_package_0309.zhaoh0309/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0309Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0309_ServiceDesc is the grpc.ServiceDesc for Zhaoh0309 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0309_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0309.sample_package_0309.zhaoh0309",
	HandlerType: (*Zhaoh0309Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Zhaoh0309_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhaoh0309.proto",
}
